version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
    - 7.26.4
  - dependency-name: ember-cli-terser
    versions:
    - 4.0.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.3.0
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.26.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.2.0
    - 10.3.0
    - 10.4.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: ember-source
    versions:
    - 3.25.0
    - 3.25.3
    - 3.26.0
    - 3.26.1
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.4.0
    - 5.5.0
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.7.0
    - 5.7.1
  - dependency-name: ember-qunit
    versions:
    - 5.1.3
    - 5.1.4
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.21.0
    - 3.0.0
    - 3.1.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: "@ember/test-helpers"
    versions:
    - 2.2.0
    - 2.2.3
  - dependency-name: ember-page-title
    versions:
    - 6.2.1
